name: local-dev-env
services:
  mpc-db:
    image: mariadb:11.4-noble
    container_name: mpc-mysql
    ports:
      - "3306:3306"
    volumes:
      - ../mysql.conf.d:/etc/mysql/conf.d/
      - ../../../mpc-backend/sql/:/docker-entrypoint-initdb.d/
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_DATABASE=mpc
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    restart: always
    networks:
      - mpc
#  init-db:
#    image: mariadb:11.4-noble
#    command:
#      - /usr/local/bin/init-docker-databases.sh
#    volumes:
#      - ../init-docker-databases.sh:/usr/local/bin/init-docker-databases.sh
#      - ../../../mpc-backend/sql/init-database.sql:/init-database.sql
#    depends_on:
#      mpc-db:
#        condition: service_healthy
#    networks:
#      - mpc
  mpc-zk:
    image: zookeeper:3.7.2
    restart: always
    ports:
      - "2181:2181"
    networks:
      - mpc
networks:
  mpc:
    driver: bridge
